export interface LocalBrand {
  id: string;
  name: string;
  nameAr: string;
  website: string;
  category: "streetwear" | "sports" | "women" | "men" | "basics" | "kids" | "accessories" | "luxury" | "marketplace";
  platform: "shopify" | "woocommerce" | "custom";
  color: string;
  description?: string;
  tags: string[];
  /** Paid feature — brand results appear first with Sponsored badge */
  featured?: boolean;
}

export const LOCAL_BRANDS: LocalBrand[] = [
  // ── 🛒 Marketplaces (multi-brand platforms) ────────────────────────────────
  {
    id: "locally",
    name: "Locally",
    nameAr: "لوكالي",
    website: "https://locallyeg.com",
    category: "marketplace",
    platform: "shopify",
    color: "#FF5733",
    description: "Egypt's biggest local brand marketplace — 100+ designers",
    tags: ["t-shirt", "dress", "bag", "accessories", "fashion"],
    featured: true,
  },
  {
    id: "genz",
    name: "GENZ",
    nameAr: "جين زد",
    website: "https://genz-s.com",
    category: "marketplace",
    platform: "shopify",
    color: "#1a1a1a",
    description: "Egyptian streetwear marketplace",
    tags: ["hoodie", "cargo", "oversized", "streetwear"],
    featured: true,
  },
  {
    id: "go-native",
    name: "Go Native",
    nameAr: "جو نيتيف",
    website: "https://gonative.eg",
    category: "marketplace",
    platform: "shopify",
    color: "#2E7D32",
    description: "Egyptian local brands in one place",
    tags: ["clothing", "bag", "handmade", "fashion"],
  },
  {
    id: "brantu",
    name: "Brantu",
    nameAr: "برانتو",
    website: "https://brantu.com",
    category: "marketplace",
    platform: "shopify",
    color: "#6A1B9A",
    description: "Designer fashion marketplace",
    tags: ["dress", "accessories", "designer", "fashion"],
  },

  // ── 🧢 Streetwear / Gen-Z ──────────────────────────────────────────────────
  {
    id: "town-team",
    name: "Town Team",
    nameAr: "تاون تيم",
    website: "https://townteam.com",
    category: "streetwear",
    platform: "shopify",
    color: "#1a1a1a",
    description: "Egypt's leading streetwear brand",
    tags: ["t-shirt", "jeans", "hoodie", "jacket", "cap"],
    featured: true,
  },
  {
    id: "dice",
    name: "Dice",
    nameAr: "دايس",
    website: "https://dice-eg.com",
    category: "streetwear",
    platform: "shopify",
    color: "#111111",
    description: "Hoodies, sweatshirts & joggers",
    tags: ["hoodie", "sweatshirt", "t-shirt", "jogger"],
    featured: true,
  },
  {
    id: "young-noise",
    name: "Young Noise",
    nameAr: "يانج نويز",
    website: "https://www.youngnoise.com",
    category: "streetwear",
    platform: "shopify",
    color: "#E53935",
    description: "Oversized shirts, hoodies & jackets",
    tags: ["hoodie", "oversized", "t-shirt", "sweater", "jacket"],
    featured: true,
  },
  {
    id: "asili",
    name: "Asili",
    nameAr: "أصيلي",
    website: "https://asilieg.com",
    category: "streetwear",
    platform: "shopify",
    color: "#4A4A4A",
    description: "Hoodies, cargos, denim & sweaters",
    tags: ["hoodie", "t-shirt", "cargo", "denim", "sweater"],
    featured: true,
  },
  {
    id: "ordinary-product",
    name: "Ordinary Product",
    nameAr: "أوردينري برودكت",
    website: "https://ordinaryproduct.com",
    category: "streetwear",
    platform: "shopify",
    color: "#2B2B2B",
    description: "Everyday basics & casual wear",
    tags: ["t-shirt", "hoodie", "sweatshirt", "basics", "casual"],
    featured: true,
  },
  {
    id: "mawlah",
    name: "Mawlah",
    nameAr: "مولاه",
    website: "https://mawlah.com",
    category: "streetwear",
    platform: "shopify",
    color: "#212121",
    description: "Graphic tees & hoodies",
    tags: ["graphic tee", "hoodie", "streetwear"],
  },
  {
    id: "haweyaa",
    name: "Haweyaa",
    nameAr: "هويا",
    website: "https://haweyaa.com",
    category: "streetwear",
    platform: "shopify",
    color: "#1B1B1B",
    description: "Hoodies & oversized shirts",
    tags: ["hoodie", "oversized", "shirt"],
  },
  {
    id: "ivarr-wear",
    name: "Ivarr Wear",
    nameAr: "إيفار ويير",
    website: "https://ivarrwear.com",
    category: "streetwear",
    platform: "shopify",
    color: "#2C2C2C",
    description: "Streetwear sets & jackets",
    tags: ["jacket", "set", "hoodie", "streetwear"],
  },
  {
    id: "flipped",
    name: "Flipped",
    nameAr: "فليبد",
    website: "https://flipped.shop",
    category: "streetwear",
    platform: "shopify",
    color: "#FF6B00",
    description: "Sweatshirts & tees",
    tags: ["sweatshirt", "tee", "hoodie"],
  },
  {
    id: "mesh-ader",
    name: "Mesh Ader",
    nameAr: "مش عارف",
    website: "https://meshader.com",
    category: "streetwear",
    platform: "shopify",
    color: "#303030",
    description: "Streetwear & hoodies",
    tags: ["streetwear", "hoodie", "urban"],
  },
  {
    id: "bazic",
    name: "Bazic",
    nameAr: "بازيك",
    website: "https://bazicstore.com",
    category: "streetwear",
    platform: "shopify",
    color: "#1A237E",
    description: "T-shirts & sweatshirts",
    tags: ["t-shirt", "sweatshirt"],
  },
  {
    id: "numu",
    name: "Numu",
    nameAr: "نومو",
    website: "https://numu.eg",
    category: "streetwear",
    platform: "shopify",
    color: "#5C35CC",
    description: "Egyptian streetwear & accessories",
    tags: ["hoodie", "t-shirt", "cap", "streetwear"],
  },
  {
    id: "one-off",
    name: "One Off",
    nameAr: "ون أوف",
    website: "https://oneoff.eg",
    category: "streetwear",
    platform: "shopify",
    color: "#222222",
    description: "Limited edition Egyptian streetwear",
    tags: ["hoodie", "limited", "streetwear"],
  },
  {
    id: "loom",
    name: "Loom",
    nameAr: "لووم",
    website: "https://loom-eg.com",
    category: "streetwear",
    platform: "shopify",
    color: "#6D4C41",
    description: "Egyptian woven fashion",
    tags: ["t-shirt", "knitwear", "streetwear"],
  },
  {
    id: "tut-brand",
    name: "Tut Brand",
    nameAr: "توت براند",
    website: "https://tutbrand.com",
    category: "streetwear",
    platform: "shopify",
    color: "#C9A14A",
    description: "Egyptian culture-inspired streetwear",
    tags: ["t-shirt", "hoodie", "pharaonic", "streetwear"],
  },
  {
    id: "nous",
    name: "Nous",
    nameAr: "نوس",
    website: "https://nous.eg",
    category: "streetwear",
    platform: "shopify",
    color: "#333",
    description: "Clean Egyptian streetwear",
    tags: ["hoodie", "t-shirt", "sweatshirt"],
  },
  {
    id: "knotted",
    name: "Knotted",
    nameAr: "كنوتد",
    website: "https://knotted.co",
    category: "streetwear",
    platform: "shopify",
    color: "#8D6E63",
    description: "Handcrafted Egyptian fashion",
    tags: ["shirt", "dress", "knitwear", "handmade"],
  },
  {
    id: "plus-cairo",
    name: "Plus Cairo",
    nameAr: "بلاس كايرو",
    website: "https://pluscairo.com",
    category: "streetwear",
    platform: "shopify",
    color: "#BF360C",
    description: "Cairo-inspired streetwear",
    tags: ["hoodie", "t-shirt", "cairo", "streetwear"],
  },

  // ── 👔 Casual Menswear ─────────────────────────────────────────────────────
  {
    id: "ravin",
    name: "Ravin",
    nameAr: "رافين",
    website: "https://shop.iravin.com",
    category: "men",
    platform: "shopify",
    color: "#2d2d2d",
    description: "Jeans, T-shirts & hoodies",
    tags: ["jeans", "t-shirt", "hoodie", "jacket"],
    featured: true,
  },
  {
    id: "concrete",
    name: "Concrete",
    nameAr: "كونكريت",
    website: "https://concrete-eg.com",
    category: "men",
    platform: "shopify",
    color: "#37474F",
    description: "Suits, shirts, trousers & jackets",
    tags: ["suit", "shirt", "trouser", "jacket"],
    featured: true,
  },
  {
    id: "myne",
    name: "MYNE",
    nameAr: "ماين",
    website: "https://myne.com.eg",
    category: "men",
    platform: "shopify",
    color: "#424242",
    description: "Casual shirts & clothing",
    tags: ["casual", "shirt", "clothing"],
  },
  {
    id: "coup",
    name: "COUP",
    nameAr: "كوب",
    website: "https://coupeg.com",
    category: "men",
    platform: "shopify",
    color: "#1C1C1C",
    description: "Menswear — jackets, shirts & trousers",
    tags: ["jacket", "shirt", "trouser", "blazer"],
  },
  {
    id: "zer0-one",
    name: "Zero One",
    nameAr: "زيرو ون",
    website: "https://zer0one.com",
    category: "men",
    platform: "shopify",
    color: "#0F0F0F",
    description: "Limited edition Egyptian menswear",
    tags: ["t-shirt", "hoodie", "jacket"],
  },
  {
    id: "ecco-eg",
    name: "Ecco Egypt",
    nameAr: "إيكو مصر",
    website: "https://ecco.com.eg",
    category: "men",
    platform: "shopify",
    color: "#8B4513",
    description: "Shoes & leather goods",
    tags: ["shoes", "leather", "boots", "loafers"],
  },

  // ── 👗 Women's Fashion ─────────────────────────────────────────────────────
  {
    id: "mamzi",
    name: "Mamzi",
    nameAr: "مامزي",
    website: "https://mamzistore.com",
    category: "women",
    platform: "shopify",
    color: "#D81B60",
    description: "Dresses, tops, trousers & skirts",
    tags: ["dress", "top", "trouser", "skirt"],
    featured: true,
  },
  {
    id: "dalydress",
    name: "Daly Dress",
    nameAr: "دالي دريس",
    website: "https://dalydress.com",
    category: "women",
    platform: "shopify",
    color: "#AD1457",
    description: "Women's dresses, casual tops & pants",
    tags: ["dress", "top", "pants"],
  },
  {
    id: "zennelle",
    name: "Zennelle",
    nameAr: "زينيل",
    website: "https://zennelle.com",
    category: "women",
    platform: "shopify",
    color: "#880E4F",
    description: "Women's fashion & clothing",
    tags: ["dress", "fashion", "women"],
  },
  {
    id: "amina-k",
    name: "Amina K",
    nameAr: "أمينة ك",
    website: "https://aminak.com",
    category: "women",
    platform: "shopify",
    color: "#C62828",
    description: "Dresses & women's fashion",
    tags: ["dress", "women", "fashion"],
  },
  {
    id: "ghayda",
    name: "Ghayda",
    nameAr: "غيداء",
    website: "https://ghayda.com",
    category: "women",
    platform: "shopify",
    color: "#8B4A6B",
    description: "Modest fashion & abayas",
    tags: ["dress", "abaya", "modest", "women"],
  },
  {
    id: "heya",
    name: "Heya",
    nameAr: "هيا",
    website: "https://heya.store",
    category: "women",
    platform: "shopify",
    color: "#F06292",
    description: "Trendy women's clothing",
    tags: ["dress", "top", "women", "trendy"],
  },
  {
    id: "clover-eg",
    name: "Clover",
    nameAr: "كلوفر",
    website: "https://clovereg.com",
    category: "women",
    platform: "shopify",
    color: "#388E3C",
    description: "Women's casual & formal wear",
    tags: ["dress", "blouse", "pants", "women"],
  },
  {
    id: "lovelle",
    name: "Lovelle",
    nameAr: "لوفيل",
    website: "https://lovelle.store",
    category: "women",
    platform: "shopify",
    color: "#FF6B9D",
    description: "Dresses & feminine fashion",
    tags: ["dress", "top", "women"],
  },
  {
    id: "azza-trends",
    name: "Azza Trends",
    nameAr: "عزا تريندز",
    website: "https://azzatrends.com",
    category: "women",
    platform: "shopify",
    color: "#C06080",
    description: "Trendy women's collections",
    tags: ["dress", "tops", "women", "fashion"],
  },
  {
    id: "house-of-nomad",
    name: "House of Nomad",
    nameAr: "هاوس أوف نومad",
    website: "https://houseofnomad.com",
    category: "women",
    platform: "shopify",
    color: "#795548",
    description: "Bohemian women's fashion",
    tags: ["dress", "bohemian", "women", "boho"],
  },
  {
    id: "koba",
    name: "Koba",
    nameAr: "كوبا",
    website: "https://koba.store",
    category: "women",
    platform: "shopify",
    color: "#F57C00",
    description: "Sustainable women's fashion",
    tags: ["dress", "sustainable", "women", "eco"],
  },

  // ── 💎 Luxury & Designer ───────────────────────────────────────────────────
  {
    id: "temraza",
    name: "Temraza",
    nameAr: "تمرازا",
    website: "https://temraza.com",
    category: "luxury",
    platform: "shopify",
    color: "#4A148C",
    description: "Couture dresses & high fashion",
    tags: ["dress", "couture", "luxury", "gown"],
    featured: true,
  },
  {
    id: "hana-el-gazar",
    name: "Hana El Gazar",
    nameAr: "هنا الجزار",
    website: "https://www.hanaelgazar.com",
    category: "luxury",
    platform: "shopify",
    color: "#D4A0A0",
    description: "High-end Egyptian fashion",
    tags: ["dress", "luxury", "designer", "fashion"],
    featured: true,
  },
  {
    id: "azza-fahmy",
    name: "Azza Fahmy",
    nameAr: "عزة فهمي",
    website: "https://www.azzafahmy.com",
    category: "luxury",
    platform: "shopify",
    color: "#C5A55A",
    description: "Iconic Egyptian jewelry",
    tags: ["jewelry", "gold", "silver", "ring", "necklace"],
    featured: true,
  },
  {
    id: "okhtein",
    name: "Okhtein",
    nameAr: "أختين",
    website: "https://okhtein.com",
    category: "luxury",
    platform: "shopify",
    color: "#212121",
    description: "Iconic Egyptian bags & accessories",
    tags: ["bag", "handbag", "accessories"],
    featured: true,
  },

  // ── 👕 Basics & Essentials ─────────────────────────────────────────────────
  {
    id: "cottonil",
    name: "Cottonil",
    nameAr: "كوتونيل",
    website: "https://cottonilegypt.com",
    category: "basics",
    platform: "shopify",
    color: "#0277BD",
    description: "Underwear, pajamas, socks & loungewear",
    tags: ["underwear", "pajama", "socks", "loungewear", "cotton"],
    featured: true,
  },
  {
    id: "mobaco",
    name: "Mobaco Cottons",
    nameAr: "موباكو",
    website: "https://mobaco.com",
    category: "basics",
    platform: "shopify",
    color: "#01579B",
    description: "Shirts, polos, knitwear & pants",
    tags: ["shirt", "polo", "knitwear", "pants"],
    featured: true,
  },
  {
    id: "yadawee",
    name: "Yadawee",
    nameAr: "يدوي",
    website: "https://yadawee.com",
    category: "basics",
    platform: "shopify",
    color: "#5D4037",
    description: "Handcrafted Egyptian cotton basics",
    tags: ["shirt", "basics", "handmade", "cotton"],
  },
  {
    id: "nile-premium",
    name: "Nile Premium",
    nameAr: "نايل بريميوم",
    website: "https://nilepremium.com",
    category: "basics",
    platform: "shopify",
    color: "#006064",
    description: "Premium Egyptian cotton essentials",
    tags: ["t-shirt", "polo", "basics", "cotton"],
  },

  // ── 👟 Sports & Active ─────────────────────────────────────────────────────
  {
    id: "tifo",
    name: "Tifo",
    nameAr: "تيفو",
    website: "https://tifo.co",
    category: "sports",
    platform: "shopify",
    color: "#00853F",
    description: "Football culture & sportswear",
    tags: ["jersey", "football", "sportswear", "fan"],
    featured: true,
  },
  {
    id: "esco",
    name: "Esco",
    nameAr: "إيسكو",
    website: "https://esco-eg.com",
    category: "sports",
    platform: "shopify",
    color: "#0050A0",
    description: "Egyptian sports & activewear",
    tags: ["jersey", "shorts", "gym", "sportswear"],
    featured: true,
  },
  {
    id: "squadra",
    name: "Squadra",
    nameAr: "سكوادرا",
    website: "https://squadra-eg.com",
    category: "sports",
    platform: "shopify",
    color: "#B71C1C",
    description: "Football kits & sportswear",
    tags: ["jersey", "football", "kit", "sportswear"],
  },

  // ── 👜 Accessories ─────────────────────────────────────────────────────────
  {
    id: "up-fuse",
    name: "Up-Fuse",
    nameAr: "أب فيوز",
    website: "https://up-fuse.com",
    category: "accessories",
    platform: "shopify",
    color: "#2E7D32",
    description: "Eco-fashion bags & accessories",
    tags: ["bag", "eco", "sustainable", "accessories"],
  },
  {
    id: "taymour-grahne",
    name: "Taymour Grahne",
    nameAr: "تيمور جراهني",
    website: "https://taymour-grahne.com",
    category: "accessories",
    platform: "shopify",
    color: "#6B4C3B",
    description: "Leather bags & accessories",
    tags: ["bag", "leather", "accessories"],
  },

  // ── 🧒 Kids ────────────────────────────────────────────────────────────────
  {
    id: "baby-tiger",
    name: "Baby Tiger",
    nameAr: "بيبي تايغر",
    website: "https://babytiger.com.eg",
    category: "kids",
    platform: "shopify",
    color: "#FF8C00",
    description: "Egyptian kids clothing",
    tags: ["kids", "baby", "clothing"],
    featured: true,
  },
];

export const BRAND_CATEGORIES = [
  { id: "all",         label: "All",         labelAr: "الكل",        emoji: "🏷️" },
  { id: "marketplace", label: "Platforms",   labelAr: "منصات",       emoji: "🛒" },
  { id: "streetwear",  label: "Streetwear",  labelAr: "ستريت وير",   emoji: "🧢" },
  { id: "men",         label: "Menswear",    labelAr: "رجالي",       emoji: "👔" },
  { id: "women",       label: "Women",       labelAr: "نسائي",       emoji: "👗" },
  { id: "basics",      label: "Basics",      labelAr: "أساسيات",     emoji: "👕" },
  { id: "luxury",      label: "Luxury",      labelAr: "فاخر",        emoji: "💎" },
  { id: "sports",      label: "Sports",      labelAr: "رياضة",       emoji: "⚽" },
  { id: "accessories", label: "Accessories", labelAr: "إكسسوارات",   emoji: "👜" },
  { id: "kids",        label: "Kids",        labelAr: "أطفال",       emoji: "🧒" },
];

/** All Shopify-powered brands (can use suggest API) */
export const SHOPIFY_BRANDS = LOCAL_BRANDS.filter((b) => b.platform === "shopify");
